import streamlit as st
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime
import json

# Page setup
st.set_page_config(page_title="CORA Dashboard", page_icon="🎯", layout="wide")

# Custom CSS
st.markdown("""
<style>
    .main-header {font-size: 2.5rem; font-weight: 700; color: #1a1a1a;}
    .metric-card {background: #f0f2f6; padding: 1rem; border-radius: 0.5rem; margin: 0.5rem 0;}
</style>
""", unsafe_allow_html=True)

# Title
st.markdown('<p class="main-header">🎯 CORA Lead Generation Dashboard</p>', unsafe_allow_html=True)
st.write("Real-time view of all leads generated by CORA")

# Connect to Google Sheets using Streamlit secrets
@st.cache_resource
def connect_to_sheets():
    try:
        credentials_dict = dict(st.secrets["google_credentials"])
        scope = ['https://spreadsheets.google.com/feeds',
                 'https://www.googleapis.com/auth/drive']
        credentials = Credentials.from_service_account_info(credentials_dict, scopes=scope)
        client = gspread.authorize(credentials)
        return client
    except Exception as e:
        st.error(f"Connection error: {e}")
        return None

# Load data from Google Sheets
@st.cache_data(ttl=300)  # Refresh every 5 minutes
def load_data():
    try:
        sheet_id = st.secrets["GOOGLE_SHEET_ID"]
        client = connect_to_sheets()
        if client:
            sheet = client.open_by_key(sheet_id).sheet1
            data = sheet.get_all_records()
            return pd.DataFrame(data)
        return pd.DataFrame()
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return pd.DataFrame()

# Load the data
with st.spinner("Loading leads from Google Sheets..."):
    df = load_data()

if not df.empty:
    # Top Metrics
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("📊 Total Leads", len(df))
    
    with col2:
        today = datetime.now().strftime('%Y-%m-%d')
        today_leads = df[df['generated_date'] == today] if 'generated_date' in df.columns else pd.DataFrame()
        st.metric("📅 Today's Leads", len(today_leads))
    
    with col3:
        cities = df['organization'].str.contains('City', case=False, na=False).sum() if 'organization' in df.columns else 0
        st.metric("🏙️ Cities", cities)
    
    with col4:
        churches = df['organization'].str.contains('Church', case=False, na=False).sum() if 'organization' in df.columns else 0
        st.metric("⛪ Churches", churches)
    
    st.markdown("---")
    
    # Filters
    col1, col2 = st.columns([3, 1])
    with col1:
        search = st.text_input("🔍 Search by name, email, or organization", "")
    with col2:
        refresh = st.button("🔄 Refresh Data")
        if refresh:
            st.cache_data.clear()
            st.rerun()
    
    # Apply search filter
    filtered_df = df.copy()
    if search:
        mask = (
            filtered_df['name'].str.contains(search, case=False, na=False) |
            filtered_df['email'].str.contains(search, case=False, na=False) |
            filtered_df['organization'].str.contains(search, case=False, na=False)
        )
        filtered_df = filtered_df[mask]
    
    # Display leads table
    st.subheader(f"📋 Leads ({len(filtered_df)} total)")
    
    # Select columns to display
    display_columns = ['name', 'title', 'organization', 'email', 'suggested_action', 'generated_date']
    available_columns = [col for col in display_columns if col in filtered_df.columns]
    
    st.dataframe(
        filtered_df[available_columns],
        use_container_width=True,
        hide_index=True,
        column_config={
            "email": st.column_config.TextColumn("Email", width="medium"),
            "name": st.column_config.TextColumn("Name", width="medium"),
        }
    )
    
    # Download button
    csv = filtered_df.to_csv(index=False)
    st.download_button(
        label="📥 Download as CSV",
        data=csv,
        file_name=f"cora_leads_{datetime.now().strftime('%Y%m%d')}.csv",
        mime="text/csv"
    )
    
    # Recent leads preview
    st.markdown("---")
    st.subheader("🆕 Most Recent Leads")
    recent_leads = filtered_df.tail(5)[['name', 'organization', 'email', 'generated_date']]
    st.dataframe(recent_leads, use_container_width=True, hide_index=True)

else:
    st.warning("⚠️ No data found. Please check your Google Sheets connection.")
    st.info("Make sure your Google Sheet ID and credentials are set up correctly in the Streamlit secrets.")

# Footer
st.markdown("---")
st.caption(f"Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Made for ApexxAdams")
```